### ISSUE TITLE
`nix-install` failing on subsequent execution

### ISSUE THREAD

**Issue by soenkehahn** [proger/nix-adhoc#1]
I've executed `./nix-install`, which gave several warnings due to missing permissions. Than I tried `sudo ./nix-install` which failed with:

```
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
./nix-install: could not download `http://hydra.nixos.org/build/17897595/download/1/nix-1.8-x86_64-linux.tar.bz2'
```

**Comment by proger** [comment]
Thanks for the report, also make sure to check updates relevant to ubuntu. I'm also going to make nix-install a part of upcast.
